// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.api.domain;

import com.api.domain.Note;

privileged aspect Note_Roo_JavaBean {
    
    public String Note.getBody() {
        return this.body;
    }
    
    public void Note.setBody(String body) {
        this.body = body;
    }
    
}
